In [1]:
import numpy as np

scores = np.array([88, 92, 76, 84, 95, 89])

print("Scores:", scores)
print("Number of dimensions:", scores.ndim)
print("Shape:", scores.shape)
print("Size:", scores.size)
print("Data type:", scores.dtype)

Scores: [88 92 76 84 95 89]
Number of dimensions: 1
Shape: (6,)
Size: 6
Data type: int64


### Part 1 - Markdown Question

One important difference between a Python list and a NumPy array is that NumPy arrays are designed for numerical calculations and can perform operations on many values at once. Python lists are more general and can contain different types of data.

In [2]:
zeros_array = np.zeros(5)
ones_array = np.ones(5)
even_values = np.arange(0, 10, 2)

print("Five zeros:", zeros_array)
print("Five ones:", ones_array)
print("Values 0, 2, 4, 6, 8:", even_values)

Five zeros: [0. 0. 0. 0. 0.]
Five ones: [1. 1. 1. 1. 1.]
Values 0, 2, 4, 6, 8: [0 2 4 6 8]


In [3]:
temperatures = np.array([72, 75, 78, 81, 79, 76, 73, 70])

print("First temperature:", temperatures[0])
print("Fourth temperature:", temperatures[3])
print("Last temperature:", temperatures[-1])

First temperature: 72
Fourth temperature: 81
Last temperature: 70


In [4]:

temperatures[3] = 82

print("Updated temperatures:", temperatures)

Updated temperatures: [72 75 78 82 79 76 73 70]


In [5]:
print("First four temperatures:", temperatures[:4])
print("Positions 2 through 5:", temperatures[2:6])
print("Every other value:", temperatures[::2])
print("Reverse order:", temperatures[::-1])

First four temperatures: [72 75 78 82]
Positions 2 through 5: [78 82 79 76]
Every other value: [72 78 79 73]
Reverse order: [70 73 76 79 82 78 75 72]


The ending index of a Python or NumPy slice is not included. For example, temperatures[2:6] starts at index 2 and stops before index 6, so it includes indexes 2, 3, 4, and 5.

In [6]:
exam_scores = np.array([
    [88, 92, 76],
    [81, 85, 90],
    [95, 89, 94],
    [78, 82, 86]
])

print("Exam scores:")
print(exam_scores)

print("Number of dimensions:", exam_scores.ndim)
print("Shape:", exam_scores.shape)
print("Size:", exam_scores.size)
print("Data type:", exam_scores.dtype)

Exam scores:
[[88 92 76]
 [81 85 90]
 [95 89 94]
 [78 82 86]]
Number of dimensions: 2
Shape: (4, 3)
Size: 12
Data type: int64


In [7]:
print("Student 1 Exam 1:", exam_scores[0, 0])
print("Student 2 Exam 3:", exam_scores[1, 2])
print("Student 4 Exam 2:", exam_scores[3, 1])

Student 1 Exam 1: 88
Student 2 Exam 3: 90
Student 4 Exam 2: 82


In [8]:

print("All exam scores for Student 1:")
print(exam_scores[0, :])

print("All students' Exam 2 scores:")
print(exam_scores[:, 1])

print("First two students and all three exams:")
print(exam_scores[:2, :])

print("Last two columns for all students:")
print(exam_scores[:, 1:])

print("First three students and last two exams:")
print(exam_scores[:3, 1:])

All exam scores for Student 1:
[88 92 76]
All students' Exam 2 scores:
[92 85 89 82]
First two students and all three exams:
[[88 92 76]
 [81 85 90]]
Last two columns for all students:
[[92 76]
 [85 90]
 [89 94]
 [82 86]]
First three students and last two exams:
[[92 76]
 [85 90]
 [89 94]]


In a two-dimensional NumPy array, the first value in array[row, column] represents the row, and the second value represents the column. The row identifies which student is selected, while the column identifies which exam is selected.

In [24]:
numbers = np.array([10, 20, 30, 40, 50])
part = numbers[:3]
print("Original numbers:", numbers)
print("Part:", part)
part[0] = 99
print("Numbers after modifying part:", numbers)
print("Part after modification:", part)

Original numbers: [10 20 30 40 50]
Part: [10 20 30]
Numbers after modifying part: [99 20 30 40 50]
Part after modification: [99 20 30]


In [10]:
numbers = np.array([10, 20, 30, 40, 50])
safe_part = numbers[:3].copy()
safe_part[0] = 99
print("Numbers:", numbers)
print("Safe part:", safe_part)

Numbers: [10 20 30 40 50]
Safe part: [99 20 30]


A NumPy view shares data with the original array, so changing the view can also change the original array. A copy creates a separate array, so changing the copy does not affect the original. This matters when working with data because sometimes we want to make changes without accidentally changing the original dataset.

In [11]:
values = np.arange(1, 13)
print("Values:", values)
print("Original shape:", values.shape)
matrix = values.reshape(3, 4)
print("3 x 4 matrix:")
print(matrix)
print("New shape:", matrix.shape)

Values: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Original shape: (12,)
3 x 4 matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
New shape: (3, 4)


In [12]:
matrix_4x3 = values.reshape(4, 3)
print("4 x 3 matrix:")
print(matrix_4x3)

4 x 3 matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
group1 = np.array([10, 20, 30])
group2 = np.array([40, 50, 60])
combined = np.concatenate((group1, group2))
print("Combined:", combined)

Combined: [10 20 30 40 50 60]


In [14]:
first_half, second_half = np.split(combined, 2)
print("First array:", first_half)
print("Second array:", second_half)

First array: [10 20 30]
Second array: [40 50 60]


The total number of values must match the requested shape because reshaping only changes how the values are arranged. An array with 12 values can be reshaped into 3 x 4 because 3 × 4 = 12. It cannot be reshaped into 5 x 3 because 5 × 3 = 15, which would require 15 values.

In [15]:
quiz_scores = np.array([
    [82, 88, 91, 85],
    [75, 79, 84, 80],
    [93, 90, 96, 94],
    [68, 72, 74, 70],
    [88, 85, 89, 92]
])
print("Quiz scores:")
print(quiz_scores)
print("Shape:", quiz_scores.shape)
print("Number of dimensions:", quiz_scores.ndim)
print("Size:", quiz_scores.size)
print("Data type:", quiz_scores.dtype)

Quiz scores:
[[82 88 91 85]
 [75 79 84 80]
 [93 90 96 94]
 [68 72 74 70]
 [88 85 89 92]]
Shape: (5, 4)
Number of dimensions: 2
Size: 20
Data type: int64


In [16]:
print("Student 3 quiz scores:")
print(quiz_scores[2, :])

Student 3 quiz scores:
[93 90 96 94]


In [ ]:
print("First three students, Quiz 2 through Quiz 4:")
print(quiz_scores[:3, 1:4])

First three students, Quiz 2 through Quiz 4:
[[88 91 85]
 [79 84 80]
 [90 96 94]]


In [20]:
adjusted_scores = quiz_scores + 2
print("Original quiz scores:")
print(quiz_scores)
print("Adjusted quiz scores:")
print(adjusted_scores)

Original quiz scores:
[[82 88 91 85]
 [75 79 84 80]
 [93 90 96 94]
 [68 72 74 70]
 [88 85 89 92]]
Adjusted quiz scores:
[[84 90 93 87]
 [77 81 86 82]
 [95 92 98 96]
 [70 74 76 72]
 [90 87 91 94]]


In [21]:
quiz_numbers = np.arange(1, 21)
quiz_matrix = quiz_numbers.reshape(5, 4)
print("Quiz numbers reshaped:")
print(quiz_matrix)
print("Shape:", quiz_matrix.shape)

Quiz numbers reshaped:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
Shape: (5, 4)


Each row represents one student, and each column represents one quiz. Checking the shape is useful because it tells us how many students and quizzes are in the array before we start analyzing the data.